//This file is autogenerated from ../../../rtl/verilog/include/orpsoc-defines.v do not change!
#ifndef _orpsoc_DEFINES_H_
#define _orpsoc_DEFINES_H_





































#define BOARD_CLOCK_PERIOD 20


#define JTAG_DEBUG
#define UART0
#define RAM_WB
#define INTGEN










#define ARBITER_IBUS_WATCHDOG

#define ARBITER_IBUS_WATCHDOG_TIMER_WIDTH 12




#define ARBITER_DBUS_WATCHDOG

#define ARBITER_DBUS_WATCHDOG_TIMER_WIDTH 12





#define ARBITER_BYTEBUS_WATCHDOG_TIMER_WIDTH 9

#endif

